services:
  app:
    container_name: app_ramais
    build:
      context: ./front
      dockerfile: ./Dockerfile
      args:
        VITE_APP_NODE_ENV: ${VITE_APP_NODE_ENV}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    environment:
      - VITE_APP_NODE_ENV=${VITE_APP_NODE_ENV}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    expose: 
      - 80
    networks:
      - dokploy-network

  api:
    image: node:18
    container_name: api_ramais
    build:
      context: ./api
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    expose:
      - 3000
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true